### ISSUE TITLE
Suggestion | totalPoints

### ISSUE THREAD

**Issue by ghost** [Androz2091/funcraft#10]
Ajouter une fonction `totalPoints` pour avoir le nombre total de point des joueurs.
Rajouter aussi le le ratio des victoires/défaite.

**Comment by Hunam6** [comment]
Le ratio win/lose est déjà implémenté, `player.game.wl` (ex : `player.blitz.wl`).

**Comment by Hunam6** [comment]
totalPoint added (PR #11)

**Comment by Androz2091** [comment]
Closed by #11
