### ISSUE TITLE
Bug [PvPSmash]

### ISSUE THREAD

**Issue by ghost** [Androz2091/funcraft#20]
Bonjour, voici un bug que j'ai découvert !

**Joueur : Dakn**

player.PvPSmash.damageCount = `176` dégats
Sur le site officiel = `176 627` dégats

💡 Ajouter aussi une fonction `totalDeath` par défaut dans le module serait cool 

Bonne journée,
 Feldup.

**Comment by Hunam6** [comment]
Fixed in the last release but not yet published on npm, I think @Androz2091 should setup a quick workflow to avoid this.
